@startuml
title Admin Login Activity Diagram
skinparam swimlaneBorderColor black
skinparam swimlaneTitleBackgroundColor #EEE
skinparam activityBackgroundColor #FEFEFE
skinparam activityArrowColor #333
skinparam activityBorderColor #333
skinparam nodesep 50
skinparam ranksep 50

|Admin_User|
|System| (Web App & Database)

|Admin_User|
start
:Access Admin Login Page;
:Enter Email & Password;
|System|
:Validate Admin Credentials;
if (Valid?) then (No)
    :Return Error Message;
    stop
else (Yes)
    :Login Admin User;
    :Redirect to Dashboard;
endif
stop
@enduml
