@startuml
title Recommender Module Activity Diagram
skinparam swimlaneBorderColor black
skinparam swimlaneTitleBackgroundColor #EEE
skinparam activityBackgroundColor #FEFEFE
skinparam activityArrowColor #333
skinparam activityBorderColor #333

|User|
|System| (Web App & Database)
|External_API| (Python Recommender Service)

|User|
start
:View Recommendations;
|System|
:Request Recommendations (User ID);
|External_API|
:Calculate Recommendations;
:Return Song IDs & Scores;
|System|
:Receive Song IDs & Scores;
:Fetch Song Details from Database;
:Display Recommendations;
stop
@enduml
