@extends('layouts.admin')

@section('title', 'Preview Recommendations')

@section('content')
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Preview Recommendations <small>Test User Feed</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row mb-4">
                    <div class="col-md-6">
                        <p>Select a user to preview their recommendation feed generated by the Python service.</p>
                    </div>
                    <div class="col-md-6 text-right">
                        <form action="{{ route('admin.retrain.process') }}" method="POST" style="display: inline-block;">
                            @csrf
                            <button type="submit" class="btn btn-warning"><i class="fa fa-refresh"></i> Force Retrain Model</button>
                        </form>
                    </div>
                </div>
                <form action="{{ route('admin.retrain.page') }}" method="GET" class="form-inline">
                    <div class="form-group">
                        <label for="user_id" style="margin-right: 10px;">Select User:</label>
                        <select name="user_id" id="user_id" class="form-control">
                            <option value="">-- Select a User --</option>
                            @foreach($users as $user)
                                <option value="{{ $user->id }}" {{ request('user_id') == $user->id ? 'selected' : '' }}>
                                    {{ $user->name }} (ID: {{ $user->id }})
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success" style="margin-left: 10px;">Get Recommendations</button>
                </form>

                <br>

                @if(isset($recommendations))
                    <h3>Recommendations for User ID: {{ request('user_id') }}</h3>
                    @if(count($recommendations) > 0)
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table">
                                <thead>
                                    <tr class="headings">
                                        <th class="column-title">Song Name</th>
                                        <th class="column-title">Score</th>
                                        <th class="column-title">Reason</th>
                                        <th class="column-title">Social Boost</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($recommendations as $rec)
                                    <tr>
                                        <td>{{ $rec['song_name'] }}</td>
                                        <td>{{ number_format($rec['score'], 4) }}</td>
                                        <td>{{ $rec['reason'] }}</td>
                                        <td>{{ number_format($rec['social_boost'] ?? 0, 2) }}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="alert alert-warning">No recommendations found for this user.</div>
                    @endif
                @endif
            </div>
        </div>
    </div>
</div>
@endsection
