[program:musicsocial-recommender]
directory=/var/www/musicsocial/recommender_service
command=/var/www/musicsocial/recommender_service/venv/bin/gunicorn -w 3 -b 127.0.0.1:5000 app:app
autostart=true
autorestart=true
stderr_logfile=/var/www/musicsocial/storage/logs/recommender.error.log
stdout_logfile=/var/www/musicsocial/storage/logs/recommender.out.log
user=root
stopasgroup=true
killasgroup=true
